<a href="https://colab.research.google.com/github/saurav-baral/Basic_Bioinformatics/blob/main/Dynamic_programming_nw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
# seq_1 = "AATTGGCC"
# seq_2 = "AATGGCC"

seq_1 = "ACGT"
seq_2 = "ACGGCT"


len(seq_1)

4

In [97]:
#scoring scheme
match, mismatch, gap = 2 , -1, -2


In [98]:
import numpy as np
#initialize two matrices
score_matrix = np.random.randint(5 ,size = (len(seq_2)+1,len(seq_1)+1))
direction_matrix = np.empty((len(seq_2)+1,len(seq_1)+1), dtype="str")
print(score_matrix)

[[2 1 3 4 3]
 [1 4 1 3 0]
 [0 1 2 1 4]
 [3 0 2 1 3]
 [4 4 1 0 4]
 [4 4 1 4 0]
 [2 0 0 2 0]]


In [99]:
#initializing gap
for columns in range(len(seq_1)+1):
  # print (score_matrix[0,columns])
  if columns == 0:
    score_matrix[0,columns] = 0
  else:
    score_matrix [0, columns] = score_matrix [0, columns-1] + gap
for row in range(len(seq_2)+1):
  if row == 0:
    score_matrix[row, 0] = 0
  else:
    score_matrix[row, 0] = score_matrix[row-1, 0] + gap
print (score_matrix)

[[  0  -2  -4  -6  -8]
 [ -2   4   1   3   0]
 [ -4   1   2   1   4]
 [ -6   0   2   1   3]
 [ -8   4   1   0   4]
 [-10   4   1   4   0]
 [-12   0   0   2   0]]


In [100]:
#initializing gap
for columns in range(len(seq_1)+1):
  # print (score_matrix[0,columns])
  if columns == 0:
    score_matrix[0,columns] = 0
  else:
    score_matrix [0, columns] = score_matrix [0, columns-1] + gap
for row in range(len(seq_2)+1):
  if row == 0:
    score_matrix[row, 0] = 0
  else:
    score_matrix[row, 0] = score_matrix[row-1, 0] + gap
# print (score_matrix)

#alignment score
for row in range(len(seq_2)+1):
  for column in range(len(seq_1)+1):
    # print (score_matrix[row,column])
    if column < len(seq_1) and row < len(seq_2):
      # print (column)
      first_seq_base = seq_1[column]
      second_seq_base = seq_2[row]
      # print(first_seq_base, second_seq_base)
      if first_seq_base == second_seq_base:
        local_score = match
      else:
        local_score = mismatch
      up_left =(score_matrix[(row+1)-1,(column+1)-1]+local_score) 
      # print("ul :",up_left)
      up =(score_matrix[(row+1)-1,(column+1)]+gap)
      # print("up:",up)
      left = (score_matrix[(row+1),(column+1)-1]+gap)
      # print("l:",left)
      score = max(up_left, up, left)
      # print (score)
      if score == up_left:
        # print ("UL")
        direction = "D"
      elif score == up:
        # print ("U")
        direction = "U"
      else:
        # print("L")
        direction = "L"
      # print (direction)
      score_matrix[(row+1),(column+1)] = score
      # print(score_matrix)
      direction_matrix[(row+1),(column+1)] = direction
      # print(direction_matrix)
    # break
  # break
      # print(score)
print (score_matrix,"\n", direction_matrix)

[[  0  -2  -4  -6  -8]
 [ -2   2   0  -2  -4]
 [ -4   0   4   2   0]
 [ -6  -2   2   6   4]
 [ -8  -4   0   4   5]
 [-10  -6  -2   2   3]
 [-12  -8  -4   0   4]] 
 [['' '' '' '' '']
 ['' 'D' 'L' 'L' 'L']
 ['' 'U' 'D' 'L' 'L']
 ['' 'U' 'U' 'D' 'L']
 ['' 'U' 'U' 'D' 'D']
 ['' 'U' 'D' 'U' 'D']
 ['' 'U' 'U' 'U' 'D']]


In [101]:
rows, columns = len(seq_2) , len(seq_1)
print (rows, columns)
aligned_seq_1 = ''
aligned_seq_2 = ''
while columns >= 1 and rows >= 1:
  direction = (direction_matrix[rows,columns])
  if direction == "D":
    aligned_seq_1 = seq_1[columns-1:columns] + aligned_seq_1
    aligned_seq_2 = seq_2[rows-1:rows] + aligned_seq_2
    rows += -1 
    columns += -1
  elif direction == "L":
    aligned_seq_1 = seq_1[columns-1:columns] + aligned_seq_1
    aligned_seq_2 = "-"+ aligned_seq_2
    columns += -1
  else:
    aligned_seq_1 = "-" + aligned_seq_1
    aligned_seq_2 = seq_2[rows-1:rows]+ aligned_seq_2
    rows += -1
  # rows += -1
  # columns += -1
  print (rows, columns)
print (aligned_seq_1,"\n",aligned_seq_2)


6 4
5 3
4 3
3 2
2 2
1 1
0 0
AC-G-T 
 ACGGCT
